-- MySQL Script generated by MySQL Workbench
-- Fri Aug 17 00:25:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cookies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cookies
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS `cookies` DEFAULT CHARACTER
SET utf8 ;
USE `cookies`
;

-- -----------------------------------------------------
-- Table `cookies`.`categories`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `cookies`.`categories`
(
  `id` INT
(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR
(50) NOT NULL,
  `description` TEXT NOT NULL,
  `imageURL` VARCHAR
(2083) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY
(`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `title_UNIQUE` ON `cookies`.`categories`
(`title` ASC);


-- -----------------------------------------------------
-- Table `cookies`.`cookieRecipe`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `cookies`.`cookieRecipe`
(
  `id` INT
(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR
(250) NULL DEFAULT NULL,
  `ingredient` LONGTEXT NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `preparation` LONGTEXT NULL DEFAULT NULL,
  `picture` LONGTEXT NULL DEFAULT NULL,
  `video` LONGTEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATE NULL DEFAULT NULL,
  `img_blob` BLOB NULL DEFAULT NULL,
  `categories` INT
(11) NULL,
  `type` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY
(`id`),
  CONSTRAINT `post_ibfk_1`
    FOREIGN KEY
(`categories`)
    REFERENCES `cookies`.`categories`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `categories` ON `cookies`.`cookieRecipe`
(`categories` ASC);


-- -----------------------------------------------------
-- Table `cookies`.`profil`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `cookies`.`profil`
(
  `id` INT
(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR
(250) NULL DEFAULT NULL,
  `firstName` VARCHAR
(250) NULL DEFAULT NULL,
  `lastName` VARCHAR
(250) NULL DEFAULT NULL,
  `email` VARCHAR
(250) NULL DEFAULT NULL,
  `password` VARCHAR
(250) NULL DEFAULT NULL,
  `imageURL` VARCHAR
(250) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY
(`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `cookies`.`profil`
(`email` ASC);


-- -----------------------------------------------------
-- Table `cookies`.`favoriesposts`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `cookies`.`favoriesposts`
(
  `profilid` INT
(11) NOT NULL,
  `cookieRecipeId` INT
(11) NOT NULL)
ENGINE = InnoDB;

CREATE INDEX `profilid` ON `cookies`.`favoriesposts`
(`profilid` ASC);

CREATE INDEX `cookieRecipeid` ON `cookies`.`favoriesposts`
(`cookieRecipeId` ASC);


SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;
